dist: xenial
git:
  submodules: false

before_install: 
- sudo apt update -y
- sudo apt install python3 python3-pip python3-virtualenv hunspell myspell-en-us -y
- virtualenv spell_pve && source spell_pve/bin/activate && pip install mistune && deactivate

script:
- source spell_pve/bin/activate && ./.CI/spellchecker.sh && deactivate
